# Generated by Django 2.2.3 on 2019-07-20 20:52

from django.db import migrations

def add_IA(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    IA_model = apps.get_model('app', 'IA')
    ia = IA_model(name="random", code="random")
    ia.save()
    IA_model2 = apps.get_model('app', 'IA')
    ia = IA_model2(name="basic", code="basic")
    ia.save()

def add_pawn_types(apps, schema_editor):
    types = {}
    types["king"] ="king"
    types["queen"] = "queen"
    types["rook"] = "rook"
    types["bishop"] = "bishop"
    types["knight"] = "knight"
    types["pawn"] = "pawn"
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    pawn_types_model = apps.get_model('app', 'PawnsType')
    for key, value in types.items():

        pawn_types = pawn_types_model(name=value, code=key)
        pawn_types.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_IA),
        migrations.RunPython(add_pawn_types),
    ]
