# Generated by Django 2.2.3 on 2019-07-22 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190720_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pawns',
            new_name='Pawn',
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
